#!/bin/bash

#########################################################
#
# This is a test script.
#
# When NetworkManager establishes connection with
# IF_CONNECTION ("Home Access Point") rsync will start
# synchronizing your /home folder with your server.
#
#


# You can connections UUIDs to be sure that you are really
# connected to your access point.
#IF_CONNECTION=("4d2c8947-4093-4fef-a929-bc8d92b77bc7")

IF_CONNECTION=("Home Access Point")

up() {
	# backup of /home folder
	rsync -avz /home user@server:/backup/home
}

